### ISSUE TITLE
在您的boot-dubbo项目中,dubbo-consumer无法找到dubbo-provider:jar的jar包

### ISSUE THREAD

**Issue by yangxiRespect** [LuoLiangDSGA/SpringBoot-Learning#1]
我在dubbo-provider项目下执行了打包命令,然后springboot:run了dubbo-provider项目,在springboot:run项目dubbo-consumer时报错
[ERROR] Failed to execute goal on project dubbo-consumer: Could not resolve dependencies for project org.boot.dubbo:dubbo-consumer:jar:1.0.0-SNAPSHOT: Could not find artifact org.boot.dubbo:dubbo-provider:jar:1.0.0-SNAPSHOT -> [Help 1]

**Comment by LuoLiangDSGA** [comment]
您mvn install了吗？

**Comment by yangxiRespect** [comment]
无法导入jar包的问题已解决了.原因修改了dubbo-provider中的方法后未升级版本,导致dubbo-consumer中映入的jar包是老版本的,没有起对应的方法.
dubbo-provider运行起来后提示:
2018-04-09 12:50:11.527  INFO 11636 --- [localhost:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2018-04-09 12:50:11.528  WARN 11636 --- [localhost:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: 拒绝连接
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_144]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_144]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.9.jar:3.4.9-1757313]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141) ~[zookeeper-3.4.9.jar:3.4.9-1757313]
是因为要在本地启动zookeeper吗?

**Comment by LuoLiangDSGA** [comment]
需要预先装好zk
